name: Flutter Inputs

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
